npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: 'B006296F-63BF-4D9A-B39C-5D91DD00242B'
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: 'B006296F-63BF-4D9A-B39C-5D91DD00242B'
