export { default as addShopping } from './add_shopping.png';
export { default as calendar } from './calendar.png';
export { default as inventory } from './inventory.png';
export { default as editCalendar } from './edit_calendar.png';
export { default as manageAccounts } from './manage_accounts.png';
export { default as menu } from './menu.png';
export { default as notifications } from './notifications.png';
export { default as schedule } from './schedule.png';
export { default as storefront } from './storefront.png';
